import type { Product } from "./store"

// <CHANGE> Created comprehensive multi-category product catalog
export const INITIAL_PRODUCTS: Product[] = [
  // WATCHES
  {
    id: "1",
    name: "Aura Majestic Gold",
    description: "A timeless masterpiece featuring 18k gold plating and sapphire crystal.",
    price: 12500,
    image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?q=80&w=1000&auto=format&fit=crop",
    category: "Watches",
    subCategory: "Luxury Analog",
    brand: "Gadgetaura",
    rating: 4.9,
    inStock: true,
    features: ["18k Gold Plated", "Automatic Movement", "Sapphire Crystal"],
    specs: {
      "Case Size": "41mm",
      Material: "Gold & Steel",
      Movement: "Self-winding Automatic",
      "Water Resistance": "100m",
      "Crystal Type": "Sapphire",
    },
  },
  {
    id: "2",
    name: "Aura Stealth Chrono",
    description: "Engineered for the daring, with deep black ceramic and emerald accents.",
    price: 9800,
    image: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?q=80&w=1000&auto=format&fit=crop",
    category: "Watches",
    subCategory: "Sport Chronograph",
    brand: "Gadgetaura",
    rating: 4.8,
    inStock: true,
    features: ["Ceramic Bezel", "Chronograph", "Super-LumiNova"],
    specs: {
      "Case Size": "44mm",
      Material: "Black Ceramic",
      Movement: "Quartz Precision",
      "Water Resistance": "200m",
      "Crystal Type": "Hardened Mineral",
    },
  },
  {
    id: "3",
    name: "Aura Horizon Limited",
    description: "Exclusive limited edition celebrating the intersection of art and engineering.",
    price: 18000,
    image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?q=80&w=1000&auto=format&fit=crop",
    category: "Watches",
    subCategory: "Limited Edition",
    brand: "Gadgetaura",
    rating: 5.0,
    inStock: true,
    features: ["Limited to 500 Pieces", "Skeleton Dial", "Titanium Case"],
    specs: {
      "Case Size": "42mm",
      Material: "Grade 5 Titanium",
      Movement: "Hand-wound Mechanical",
      "Water Resistance": "50m",
      "Limited Edition": "500 pieces",
    },
  },
  {
    id: "4",
    name: "Aura Emerald Executive",
    description: "Elegance meets performance with a deep green sunray dial.",
    price: 11000,
    image: "https://images.unsplash.com/photo-1548171916-042ad9159303?q=80&w=1000&auto=format&fit=crop",
    category: "Watches",
    subCategory: "Dress Watch",
    brand: "Gadgetaura",
    rating: 4.7,
    inStock: true,
    features: ["Emerald Sunray Dial", "Stainless Steel", "Date Window"],
    specs: {
      "Case Size": "40mm",
      Material: "904L Steel",
      Movement: "Perpetual Rotor",
      "Water Resistance": "100m",
      "Crystal Type": "Sapphire",
    },
  },

  // HEADPHONES & AUDIO
  {
    id: "5",
    name: "SonicWave Pro ANC",
    description: "Premium over-ear headphones with adaptive noise cancellation and 40-hour battery life.",
    price: 349,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1000&auto=format&fit=crop",
    category: "Headphones & Audio",
    subCategory: "Over-Ear Wireless",
    brand: "Gadgetaura",
    rating: 4.8,
    inStock: true,
    features: ["Active Noise Cancellation", "40H Battery", "Spatial Audio", "Premium Leather Cushions"],
    specs: {
      "Driver Size": "40mm Dynamic",
      "Battery Life": "40 hours",
      Connectivity: "Bluetooth 5.3, USB-C",
      "Noise Cancellation": "Adaptive ANC",
      "Frequency Response": "20Hz - 40kHz",
    },
  },
  {
    id: "6",
    name: "AuraEars Elite TWS",
    description: "True wireless earbuds with hi-res audio, ANC, and premium charging case.",
    price: 199,
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?q=80&w=1000&auto=format&fit=crop",
    category: "Headphones & Audio",
    subCategory: "True Wireless Earbuds",
    brand: "Gadgetaura",
    rating: 4.6,
    inStock: true,
    features: ["Hi-Res Audio", "ANC + Transparency", "Wireless Charging", "IPX5 Waterproof"],
    specs: {
      "Driver Size": "10mm Graphene",
      "Battery Life": "8h (30h with case)",
      Connectivity: "Bluetooth 5.3",
      "Noise Cancellation": "Hybrid ANC",
      "Water Resistance": "IPX5",
    },
  },
  {
    id: "7",
    name: "BassForge Studio",
    description: "Studio-grade wired headphones designed for audiophiles and producers.",
    price: 279,
    image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?q=80&w=1000&auto=format&fit=crop",
    category: "Headphones & Audio",
    subCategory: "Studio Monitor",
    brand: "Gadgetaura",
    rating: 4.9,
    inStock: true,
    features: ["Planar Magnetic Drivers", "Detachable Cable", "Open-Back Design", "Velour Cushions"],
    specs: {
      "Driver Type": "50mm Planar Magnetic",
      Impedance: "32 Ohms",
      "Frequency Response": "10Hz - 50kHz",
      Cable: "3.5mm + 6.3mm adapter",
      Weight: "380g",
    },
  },

  // SMART GADGETS
  {
    id: "8",
    name: "PulseTrack Ultra Smartwatch",
    description: "Advanced fitness smartwatch with ECG, GPS, and 10-day battery life.",
    price: 399,
    image: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?q=80&w=1000&auto=format&fit=crop",
    category: "Smart Gadgets",
    subCategory: "Smartwatch",
    brand: "Gadgetaura",
    rating: 4.7,
    inStock: true,
    features: ["ECG Monitoring", "Built-in GPS", "SpO2 Sensor", "10-Day Battery", "AMOLED Display"],
    specs: {
      "Display Size": "1.43\" AMOLED",
      "Battery Life": "10 days typical use",
      Sensors: "Heart Rate, ECG, SpO2, GPS, Compass",
      "Water Resistance": "5ATM (50m)",
      Compatibility: "iOS & Android",
    },
  },
  {
    id: "9",
    name: "VitalRing Gen 3",
    description: "Sleek smart ring that tracks sleep, heart rate, and activity 24/7.",
    price: 299,
    image: "https://images.unsplash.com/photo-1611652022419-a9419f74343a?q=80&w=1000&auto=format&fit=crop",
    category: "Smart Gadgets",
    subCategory: "Smart Ring",
    brand: "Gadgetaura",
    rating: 4.5,
    inStock: true,
    features: ["Sleep Tracking", "Heart Rate Variability", "Temperature Sensor", "7-Day Battery"],
    specs: {
      Material: "Titanium",
      "Battery Life": "7 days",
      Sensors: "PPG Heart Rate, Temperature, Accelerometer",
      "Water Resistance": "10ATM (100m)",
      "Available Sizes": "6-13",
    },
  },
  {
    id: "10",
    name: "FitBand Pro Tracker",
    description: "Lightweight fitness band with color display and 14-day battery life.",
    price: 89,
    image: "https://images.unsplash.com/photo-1557935728-e6d1eaabe558?q=80&w=1000&auto=format&fit=crop",
    category: "Smart Gadgets",
    subCategory: "Fitness Band",
    brand: "Gadgetaura",
    rating: 4.4,
    inStock: true,
    features: ["Color AMOLED", "14-Day Battery", "50+ Sport Modes", "Sleep Tracking"],
    specs: {
      "Display Size": "1.1\" AMOLED",
      "Battery Life": "14 days",
      Sensors: "Heart Rate, SpO2, Accelerometer",
      "Water Resistance": "5ATM",
      Weight: "24g",
    },
  },

  // TRENDING ACCESSORIES
  {
    id: "11",
    name: "HyperCharge 100W GaN",
    description: "Ultra-compact 100W GaN charger with 3 ports for all your devices.",
    price: 69,
    image: "https://images.unsplash.com/photo-1591290619762-c588f7caaa5a?q=80&w=1000&auto=format&fit=crop",
    category: "Trending Accessories",
    subCategory: "Charger",
    brand: "Gadgetaura",
    rating: 4.8,
    inStock: true,
    features: ["100W Total Output", "GaN Technology", "3 Ports (2x USB-C, 1x USB-A)", "Foldable Plug"],
    specs: {
      "Total Output": "100W",
      Ports: "2x USB-C, 1x USB-A",
      Technology: "GaN III",
      "Input Voltage": "100-240V",
      Weight: "195g",
    },
  },
  {
    id: "12",
    name: "PowerCore Ultra 30000mAh",
    description: "Massive capacity power bank with 65W fast charging and premium aluminum build.",
    price: 129,
    image: "https://images.unsplash.com/photo-1609592806508-aa6c6c5b3a46?q=80&w=1000&auto=format&fit=crop",
    category: "Trending Accessories",
    subCategory: "Power Bank",
    brand: "Gadgetaura",
    rating: 4.7,
    inStock: true,
    features: ["30000mAh Capacity", "65W PD Charging", "Digital Display", "Aluminum Body"],
    specs: {
      Capacity: "30000mAh",
      "Max Output": "65W",
      Ports: "2x USB-C, 1x USB-A",
      "Recharge Time": "3.5 hours",
      Weight: "560g",
    },
  },
  {
    id: "13",
    name: "DeskGlow RGB Light Bar",
    description: "Premium RGB monitor light bar with smart controls and auto-dimming.",
    price: 79,
    image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1000&auto=format&fit=crop",
    category: "Trending Accessories",
    subCategory: "Desk Accessory",
    brand: "Gadgetaura",
    rating: 4.6,
    inStock: true,
    features: ["16M RGB Colors", "Auto-Dimming", "App Control", "USB-C Powered"],
    specs: {
      Length: "45cm",
      "Color Temperature": "2700K - 6500K",
      Brightness: "1000 lumens",
      Control: "Touch + App",
      Power: "USB-C 5V",
    },
  },
  {
    id: "14",
    name: "MagStand Pro Aluminum",
    description: "Premium MagSafe-compatible phone stand with adjustable angles.",
    price: 49,
    image: "https://images.unsplash.com/photo-1601593346740-925612772716?q=80&w=1000&auto=format&fit=crop",
    category: "Trending Accessories",
    subCategory: "Phone Stand",
    brand: "Gadgetaura",
    rating: 4.5,
    inStock: true,
    features: ["MagSafe Compatible", "Adjustable Angle", "Aluminum Body", "Weighted Base"],
    specs: {
      Material: "Aluminum Alloy",
      Compatibility: "MagSafe iPhones & Cases",
      "Angle Range": "0-90 degrees",
      Weight: "320g",
      Finish: "Anodized Space Gray",
    },
  },
  {
    id: "15",
    name: "CableOrganizer Pro Kit",
    description: "Premium cable management kit with magnetic holders and cable wraps.",
    price: 29,
    image: "https://images.unsplash.com/photo-1625948515291-69613efd103f?q=80&w=1000&auto=format&fit=crop",
    category: "Trending Accessories",
    subCategory: "Cable Management",
    brand: "Gadgetaura",
    rating: 4.3,
    inStock: true,
    features: ["Magnetic Holders", "Silicone Wraps", "Adhesive Mounts", "Premium Materials"],
    specs: {
      Includes: "6x Magnetic Clips, 8x Cable Wraps, 4x Adhesive Mounts",
      Material: "Silicone + ABS",
      "Cable Capacity": "Up to 10mm diameter",
      Color: "Black",
      Weight: "85g",
    },
  },
  {
    id: "16",
    name: "AirFlow Laptop Stand",
    description: "Ergonomic aluminum laptop stand with improved airflow and cable management.",
    price: 59,
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=1000&auto=format&fit=crop",
    category: "Trending Accessories",
    subCategory: "Laptop Stand",
    brand: "Gadgetaura",
    rating: 4.7,
    inStock: true,
    features: ["Adjustable Height", "Aluminum Build", "Improved Airflow", "Anti-Slip Pads"],
    specs: {
      Material: "Aluminum Alloy",
      "Height Range": "8-18cm",
      Compatibility: "10-17 inch laptops",
      "Max Load": "5kg",
      Weight: "850g",
    },
  },
]
